### ISSUE TITLE
[Feature] Choose order of all options

### ISSUE THREAD

**Issue by NovaliX-Dev** [Lutetium-Vanadium/requestty#13]
#Why ?
Certains programs need to let the user choose the order of certain things. For example, a tool allow to combine data all together and the user can choose in which order to combine it.

#How will it work ?
Similarly to Multi-Select : the space key is used to select an option, the arrows to navigate threw or move the selected option and the enter key to finalize the order.

For the returned value, it can be a Vector containing the ordered IDs of the options. The IDs will be just the index of them in the list given to the question constructor.

I don't think the separators sill be necessary, because the user will mix the options up.

**Comment by Lutetium-Vanadium** [comment]
This is a very good feature to add. For the returned value (similar to multi-select) it should return a [`Vec<ListItem>`](https://docs.rs/requestty/latest/requestty/enum.Answer.html#variant.ListItems), rather than just `Vec<usize>`.

Would you like to create a PR to add it? Otherwise, I'm happy to implement it too.

**Comment by NovaliX-Dev** [comment]
I'm not able to do it right now, but sure at the end of the vacation i can try to implement it.

**Comment by NovaliX-Dev** [comment]
I had made a PR to implement it ([this pr](https://github.com/Lutetium-Vanadium/requestty/pull/16)), so i think we can close this issue.
