### ISSUE TITLE
default for input returns empty value

### ISSUE THREAD

**Issue by davidanthoff** [Lutetium-Vanadium/requestty#7]
It seems to me that if I specify a default for an input prompt, and then the user just presses Enter, we get an empty string returned, rather than the default value. The docs say the default should be returned, and that is also what would help us :)

**Comment by Lutetium-Vanadium** [comment]
The initial behaviour was meant to be that, but it seems some feature addition broke it.

However, since the default can be auto-completed, entering an empty string to return the default value seems slightly weird to me. Also, like before the default being returned cannot be a regular behaviour for all empty strings, since that disallows entering empty strings. Instead it would only return the default if the user hadn't made any changes to the string.

From a usability standpoint, I am leaning towards updating the docs to reflect the current behaviour. Is there any reason why the default value being returned for an empty string would be preferred?

**Comment by davidanthoff** [comment]
I think what I really would like is some way to start the prompt with an initial value where things start out _as if_ the user had just typed exactly that value in by hand. I imagine that the prompt would start out with that value entered, the cursor is at the end of those characters and the user could then either delete that value with backspace etc, or add more characters etc. Essentially a way to start out with an initial value without having to use auto-complete.

Maybe that is actually just a distinct concept from a default value, where the idea seems to be that if the user does not enter anything but presses Enter without any input, that value is going to be used? So maybe there should be another method `initial_value` that is distinct from `default`?

Also, it seems to me that if `default` is specified, in general it just isn't possible to return an empty string, right? Isn't a default value simply a rule that if the user doesn't enter anything, then the default value is used?

**Comment by Lutetium-Vanadium** [comment]
Hmm, I get what you mean. It does make sense to have `default` return on an empty string, so the earlier behaviour is correct. I'll fix the implementation to reflect what the docs say.
